// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!

#include "PFAdminExportMasterPlayerData.h"
#include "PlayFabProxy.h"
#include "PlayFab.h"

UPFAdminExportMasterPlayerData::UPFAdminExportMasterPlayerData(const FObjectInitializer& ObjectInitializer)
    : Super(ObjectInitializer)
    , SuccessDelegate(PlayFab::UPlayFabAdminAPI::FExportMasterPlayerDataDelegate::CreateUObject(this, &ThisClass::OnSuccessCallback))
{
}

UPFAdminExportMasterPlayerData* UPFAdminExportMasterPlayerData::ExportMasterPlayerData(class APlayerController* PlayerController, const FBPAdminExportMasterPlayerDataRequest& InExportMasterPlayerDataRequest)
{
    UPFAdminExportMasterPlayerData* Proxy = NewObject<UPFAdminExportMasterPlayerData>();
    Proxy->PlayerControllerWeakPtr = PlayerController;
    Proxy->Request = InExportMasterPlayerDataRequest;
    
    return Proxy;
}

void UPFAdminExportMasterPlayerData::Activate()
{
    // grab the module, so we can get a valid pointer to the client API
    PlayFabAdminPtr AdminAPI = IPlayFabModuleInterface::Get().GetAdminAPI();

    bool CallResult = false;

    if (AdminAPI.IsValid())
    {
        CallResult = AdminAPI->ExportMasterPlayerData(Request.Data, SuccessDelegate, ErrorDelegate);
    }

    if (CallResult == false)
        OnFailure.Broadcast();
}

void UPFAdminExportMasterPlayerData::OnSuccessCallback(const PlayFab::AdminModels::FExportMasterPlayerDataResult& Result)
{
    FBPAdminExportMasterPlayerDataResult BPResult;
     BPResult.Data = Result;
     OnSuccess.Broadcast(BPResult);
}
