// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminDeleteMasterPlayerAccount.generated.h"

UCLASS(MinimalAPI)
class UPFAdminDeleteMasterPlayerAccount : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminDeleteMasterPlayerAccountResultDelegate OnSuccess;

    // Removes a master player account entirely from all titles and deletes all associated data
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Account Management")
        static UPFAdminDeleteMasterPlayerAccount* DeleteMasterPlayerAccount(class APlayerController* PlayerController, const FBPAdminDeleteMasterPlayerAccountRequest& InDeleteMasterPlayerAccountRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminDeleteMasterPlayerAccountRequest Request;
    PlayFab::UPlayFabAdminAPI::FDeleteMasterPlayerAccountDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FDeleteMasterPlayerAccountResult& Result);
};
