// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminExportMasterPlayerData.generated.h"

UCLASS(MinimalAPI)
class UPFAdminExportMasterPlayerData : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminExportMasterPlayerDataResultDelegate OnSuccess;

    // Exports all associated data of a master player account
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Account Management")
        static UPFAdminExportMasterPlayerData* ExportMasterPlayerData(class APlayerController* PlayerController, const FBPAdminExportMasterPlayerDataRequest& InExportMasterPlayerDataRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminExportMasterPlayerDataRequest Request;
    PlayFab::UPlayFabAdminAPI::FExportMasterPlayerDataDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FExportMasterPlayerDataResult& Result);
};
