// This is automatically generated by PlayFab SDKGenerator. DO NOT modify this manually!
#pragma once

#include "CoreMinimal.h"
#include "PlayFabProxyBaseModel.h"
#include "Core/PlayFabAdminAPI.h"
#include "Core/PlayFabAdminDataModels.h"
#include "Proxy/PlayFabAdminBPDataModels.h"
#include "PFAdminGetPlayedTitleList.generated.h"

UCLASS(MinimalAPI)
class UPFAdminGetPlayedTitleList : public UPlayFabProxyBase
{
    GENERATED_UCLASS_BODY()
public:

    UPROPERTY(BlueprintAssignable)
        FBPAdminGetPlayedTitleListResultDelegate OnSuccess;

    // Get the list of titles that the player has played
    UFUNCTION(BlueprintCallable, meta = (BlueprintInternalUseOnly = "true"), Category = "PlayFab|Admin|Account Management")
        static UPFAdminGetPlayedTitleList* GetPlayedTitleList(class APlayerController* PlayerController, const FBPAdminGetPlayedTitleListRequest& InGetPlayedTitleListRequest);

    // UOnlineBlueprintCallProxyBase interface
    virtual void Activate() override;
    // End of UOnlineBlueprintCallProxyBase interface

private:
    FBPAdminGetPlayedTitleListRequest Request;
    PlayFab::UPlayFabAdminAPI::FGetPlayedTitleListDelegate SuccessDelegate;

    void OnSuccessCallback(const PlayFab::AdminModels::FGetPlayedTitleListResult& Result);
};
